### ISSUE TITLE
关于使用commentView搭建评论视图

### ISSUE THREAD

**Issue by RidiculousDoge** [Rainy-Imola/AppFrontend#40]
现在能拿到数据但是显示不了，不知道是组件使用问题还是主从线程ui更新的问题，已经给原po提交了issue但还没回https://github.com/Jidcoo/CommentView/issues/5
xdjm们有空可以帮忙一起看看otz

**Comment by RidiculousDoge** [comment]
在/gurui分支里，写完了没好意思merge（

**Comment by Lajizz** [comment]
哪个动态有评论啊，我找了一下没找到。😢

**Comment by RidiculousDoge** [comment]
> 哪个动态有评论啊，我找了一下没找到。😢

最下面那个，reconstruct下面我post了一条
