### ISSUE TITLE
动态获取接口已经修改，麻烦相应更新一下前端的请求路径

### ISSUE THREAD

**Issue by Snowfall99** [Rainy-Imola/AppFrontend#59]
具体更改如下：
1. 获取全部动态的api路径变为/msgboard/{user_id}
2. 获取动态详细信息的api路径变为/msgboard/{message_id}/{user_id}
增加了点赞相关接口，对应api路径为/msgboard/like/{user_id}，具体内容请查看messageController.java文件
请求对应增加动态点赞按钮，另外请求点赞按钮在点赞和取消赞之后有外观上的区别

**Comment by Snowfall99** [comment]
为了保证能正常使用，目前还没有进行merge，相应的修改在like分支中

**Comment by RidiculousDoge** [comment]
前端接口已经更新，点赞功能待开发
